<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="admin-PC" failures="2" tests="2" name="Default test(failed)" time="0.08" errors="0" timestamp="03 Mar 2022 14:13:34 GMT">
  <testcase classname="A4_FailureScreenShot.A18_RunOnlyFailedTest" name="sub" time="0.023">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zeroat A4_FailureScreenShot.A18_RunOnlyFailedTest.sub(A18_RunOnlyFailedTest.java:14)... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- sub -->
  <testcase classname="A4_FailureScreenShot.A18_RunOnlyFailedTest" name="mul" time="0.002">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zeroat A4_FailureScreenShot.A18_RunOnlyFailedTest.mul(A18_RunOnlyFailedTest.java:19)... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- mul -->
  <testcase classname="A4_FailureScreenShot.A18_RunOnlyFailedTest" name="add" time="0.0">
    <ignored/>
  </testcase> <!-- add -->
  <testcase classname="A4_FailureScreenShot.A18_RunOnlyFailedTest" name="div" time="0.0">
    <ignored/>
  </testcase> <!-- div -->
</testsuite> <!-- Default test(failed) -->
